# Generated by Django 4.0.4 on 2022-04-23 20:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='user_id')),
                ('username', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('date_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('tree_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='tree_ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Type', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TreeAPI.user')),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportType', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('success', models.BooleanField()),
                ('duration', models.DurationField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TreeAPI.user')),
            ],
        ),
    ]
