# Generated by Django 4.0.4 on 2022-05-08 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('tree_ID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('Type', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_trees', models.ManyToManyField(to='TreeAPI.tree')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Journey Title', max_length=50)),
                ('transportType', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('success', models.BooleanField()),
                ('duration', models.DurationField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TreeAPI.tree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
