# Generated by Django 4.0.4 on 2022-04-23 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TreeAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='tree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TreeAPI.tree'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TreeAPI.user'),
        ),
    ]
