# Generated by Django 4.0.4 on 2022-05-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeAPI', '0002_remove_tree_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='lat',
            field=models.DecimalField(decimal_places=14, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='long',
            field=models.DecimalField(decimal_places=14, max_digits=17, null=True),
        ),
    ]
