# Generated by Django 4.0.4 on 2022-04-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeAPI', '0002_journey_tree_alter_tree_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='title',
            field=models.CharField(default='Journey Title', max_length=50),
        ),
    ]
