# Generated by Django 3.2.12 on 2022-04-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeAPI', '0002_auto_20220423_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserKey', models.UUIDField()),
                ('transportType', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('success', models.BooleanField()),
                ('duration', models.DurationField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
