# Generated by Django 3.2.12 on 2022-04-25 22:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TreeAPI', '0003_journey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='id',
        ),
        migrations.AddField(
            model_name='journey',
            name='tree',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TreeAPI.tree'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='UserKey',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UserKey'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='tree_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='tree_ID'),
        ),
    ]
