# Generated by Django 4.0.4 on 2022-05-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeAPI', '0006_remove_journey_success_alter_journey_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
