# Generated by Django 4.0.4 on 2022-05-08 22:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TreeAPI', '0007_alter_journey_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='id',
        ),
        migrations.AddField(
            model_name='journey',
            name='journey_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='tree_ID'),
        ),
    ]
